# Generated by Django 5.2.8 on 2025-11-18 15:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_id', models.CharField(max_length=255, unique=True)),
                ('sid', models.CharField(max_length=255, unique=True)),
                ('channel_name', models.CharField(db_index=True, max_length=255)),
                ('recording_uid', models.CharField(default='999999', max_length=50)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('stopped_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('recording', 'Recording'), ('stopped', 'Stopped'), ('uploaded', 'Uploaded'), ('failed', 'Failed')], default='recording', max_length=20)),
                ('s3_bucket', models.CharField(blank=True, max_length=255)),
                ('s3_file_list', models.TextField(blank=True, help_text='JSON list of recording files')),
                ('mode', models.CharField(default='mix', help_text='Recording mode: mix or individual', max_length=20)),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['-started_at'], name='core_record_started_e01631_idx'), models.Index(fields=['channel_name', '-started_at'], name='core_record_channel_44f858_idx')],
            },
        ),
    ]
